ТЗ-16
LenzFF/shareit-with-docker pull request #1
Opened 2023-06-25 22:04 UTC by LenzFF

Итерация 1

2023-06-26 19:30 UTC, db-exp requested changes

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        getUserOrThrowException(id);
проверять при удалении не обязательно - запрос не упадет, только если тесты при сборке того требуют

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private String description;
можно Size добавить

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        if (item.getRequest() != null) itemDto.setRequestId(item.getRequest().getId());
старайся избегать "однострочников". Самая распространенная ошибка - начинают добавлять еще код, забывая, что if будет работать только на первую строку

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String description;
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private final UserRepository userStorage;
лучше "чужие" сервисы, а не репозитории, так можно уменьшить связность, тем самым улучшив дизайн сервиса

2023-06-26 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private String description;
можно еще Size

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") long userId,
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                    @RequestBody @Valid CommentDto commentDto) {
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull(groups = {Marker.OnCreate.class})
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                        @Valid @RequestBody ItemRequestDto itemRequestDto) {
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotBlank
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@RequestBody @Validated(Marker.OnCreate.class) UserDto userDto) {
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable long id, @RequestBody @Validated(Marker.OnUpdate.class) UserDto userDto) {
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/dto/Marker.java
> +public interface Marker {
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotEmpty(groups = {Marker.OnCreate.class}, message = "Email не может быть пустым")
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(groups = {Marker.OnCreate.class})
на server части не должно быть валидации по ТЗ

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse methodArgumentNotValidException(final MethodArgumentNotValidException e) {
такие ошибки должны отлавливаться на gateway

2023-06-26 19:30 UTC, db-exp commented on server/pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
в server не нужна валидация

2023-06-26 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "ALL":
минорное - можно через enum

2023-06-26 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
Можно еще Size

2023-06-26 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String description;
Можно еще Size

2023-06-26 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String text;
можно еще Size

2023-06-26 20:52 UTC, LenzFF commented on server/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse methodArgumentNotValidException(final MethodArgumentNotValidException e) {
Убрал отслеживание, и без него все работает)

2023-06-26 20:52 UTC, LenzFF commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "ALL":
Согласен

2023-06-26 20:54 UTC, LenzFF commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private final UserRepository userStorage;
Согласен!
Уже был такой комментарий, когда сдавал 15-е ТЗ 2 дня назад)
Уже если переделывать, то везде, а со временем сейчас сложно, нужно скорее за диплом приниматься.
Можно, пожалуйста, так оставим)

2023-06-27 04:46 UTC, db-exp approved these changes

2023-06-27 07:12 UTC, merged